mutation createSubscriber @auth(level: PUBLIC) {
  subscriber_insert(data: {email: "test@example.com"})
}

query listProducts @auth(level: PUBLIC) {
  products {
    id
    name
    price
  }
}

mutation updateProductStock @auth(level: USER) {
  product_update(id: "some-uuid", data: {stockQuantity: 100})
}

query listOrders @auth(level: USER) {
  orders {
    id
    orderNumber
    customerName
  }
}