type Product @table {
  name: String!
  price: Float!
  slug: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  imageUrls: [String]
  category: Category
  stockQuantity: Int
}

type BlogPost @table {
  title: String!
  slug: String!
  publishedAt: Timestamp!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  author: String
  content: String
  tags: [String]
  imageUrl: String
}

type Category @table {
  name: String!
  slug: String!
  createdAt: Timestamp!
  description: String
}

type Order @table {
  orderNumber: String!
  totalAmount: Float!
  orderStatus: String!
  createdAt: Timestamp!
  customerName: String
  customerEmail: String
  shippingAddress: String
}

type OrderItem @table {
  quantity: Int!
  priceAtPurchase: Float!
  order: Order!
  product: Product!
}

type Subscriber @table {
  email: String!
  createdAt: Timestamp!
}